Борисенко Дмитрий Антонович РИ-230945

In [2]:
import torch
import numpy as np
import time

# Задание 1: Создание и манипуляции с тензорами

1.1 Создание тензоров

In [3]:
# - Тензор размером 3x4, заполненный случайными числами от 0 до 1
random_tensor = torch.rand((3, 4))
# - Тензор размером 2x3x4, заполненный нулями
zeros_tensor = torch.zeros((2, 3, 4))
# - Тензор размером 5x5, заполненный единицами
one_tensor = torch.ones((5, 5))
# - Тензор размером 4x4 с числами от 0 до 15 (используйте reshape)
reshaped_tensor = torch.arange(0, 16).reshape((4, 4))
reshaped_tensor

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

1.2 Операции с тензорами

In [4]:
# Дано: тензор A размером 3x4 и тензор B размером 4x3
A = torch.rand((3, 4))
B = torch.rand((4, 3))
# - Транспонирование тензора A
A_T = A.T
# - Матричное умножение A и B
AB = A @ B
# - Поэлементное умножение A и транспонированного B
B_T = B.T
D = A * B_T
# - Вычислите сумму всех элементов тензора A
sum = A.sum()
sum

tensor(6.1403)

1.3 Индексация и срезы

In [5]:
# Создайте тензор размером 5x5x5
tensor = torch.randint(0, 100, (5, 5, 5))
print(tensor)
# Извлеките:
# - Первую строку
print(tensor[:, 0, :])
# - Последний столбец
print(tensor[:, :, -1])
# - Подматрицу размером 2x2 из центра тензора
print(tensor[1:3, 1:3, 1:3])
# - Все элементы с четными индексами
print(tensor[::2, ::2, ::2])

tensor([[[56, 93, 12,  9, 84],
         [58, 51, 29,  9, 66],
         [14, 99, 51, 84, 17],
         [99, 88, 30, 83, 84],
         [14, 17, 28, 37, 47]],

        [[89, 76, 30, 38, 97],
         [38, 68, 21, 46, 97],
         [99, 72, 29, 64, 36],
         [65, 31, 45, 50, 97],
         [24, 13, 15, 73, 19]],

        [[47, 85, 62, 50, 54],
         [22,  8, 12, 98, 69],
         [53, 29, 16, 48, 49],
         [57, 52, 36, 50, 24],
         [15, 24, 40, 34, 37]],

        [[ 1,  9, 23, 43, 95],
         [20, 73, 64, 46, 32],
         [43, 17,  2, 62,  0],
         [82, 43, 30, 97, 71],
         [16, 68, 27, 84, 67]],

        [[58, 36, 60, 96,  7],
         [51, 49, 62, 68, 48],
         [23, 65, 13, 83,  9],
         [ 2, 38, 38, 35, 59],
         [71, 61, 12, 63, 22]]])
tensor([[56, 93, 12,  9, 84],
        [89, 76, 30, 38, 97],
        [47, 85, 62, 50, 54],
        [ 1,  9, 23, 43, 95],
        [58, 36, 60, 96,  7]])
tensor([[84, 66, 17, 84, 47],
        [97, 97, 36, 97, 19],
    

1.4 Работа с формами

In [6]:
# Создайте тензор размером 24 элемента
tensor = torch.arange(0, 24)
# Преобразуйте его в формы:
# - 2x12
print(tensor.reshape((2, 12)))
# - 3x8
print(tensor.reshape((3, 8)))
# - 4x6
print(tensor.reshape((4, 6)))
# - 2x3x4
print(tensor.reshape((2, 3, 4)))
# - 2x2x2x3
print(tensor.reshape((2, 2, 2, 3)))

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[[ 0,  1,  2],
          [ 3,  4,  5]],

         [[ 6,  7,  8],
          [ 9, 10, 11]]],


        [[[12, 13, 14],
          [15, 16, 17]],

         [[18, 19, 20],
          [21, 22, 23]]]])


# Задание 2: Автоматическое дифференцирование

2.1 Простые вычисления с градиентами

In [7]:
# Создайте тензоры x, y, z с requires_grad=True
x = torch.tensor([2.0, 3.0], requires_grad=True)
y = torch.tensor([4.0, 5.0], requires_grad=True)
z = torch.tensor([1.0, 6.0], requires_grad=True)
# Вычислите функцию: f(x,y,z) = x^2 + y^2 + z^2 + 2*x*y*z
f = x ** 2 + y ** 2 + z ** 2 + 2*x*y*z
f_sum = f.sum()
print(f'x = {x}, y = {y}, z = {z}')
print(f'f = {f}')
print(f'f.sum() = {f_sum}')
f_sum.backward()
# Найдите градиенты по всем переменным
print(f'x.grad = {x.grad}')
# 2 * [2, 3] + [2 * 4 * 1, 2 * 5 * 6] = [4 + 8, 6 + 60] = [12, 66]
print(f'y.grad = {y.grad}')
print(f'z.grad = {z.grad}')

x = tensor([2., 3.], requires_grad=True), y = tensor([4., 5.], requires_grad=True), z = tensor([1., 6.], requires_grad=True)
f = tensor([ 37., 250.], grad_fn=<AddBackward0>)
f.sum() = 287.0
x.grad = tensor([12., 66.])
y.grad = tensor([12., 46.])
z.grad = tensor([18., 42.])


2.2 Градиент функции потерь

In [8]:
# Реализуйте функцию MSE (Mean Squared Error):
# MSE = (1/n) * Σ(y_pred - y_true)^2
# где y_pred = w * x + b (линейная функция)
# Найдите градиенты по w и b
def MSE(y_pred, y_true):
  return torch.mean((y - y_true) ** 2)


x = torch.tensor([[2.0, 3.0, 4.0],
                  [4.0, 4.0, 3.0],
                  [2.0, 5.0, 4.0]]
                 )
w = torch.tensor([13.2, 5.7, 4.1], requires_grad=True)
b = torch.tensor(0.3, requires_grad=True)
y_true = torch.tensor([100.0, 200.0, 300.0])
y = x @ w + b
loss = MSE(y, y_true)

loss.backward()
print(f'w.grad = {w.grad}')
print(f'b.grad = {b.grad}')

w.grad = tensor([ -655.7333, -1139.0667,  -938.8000])
b.grad = -253.33334350585938


2.3 Цепное правило

In [9]:
# Реализуйте составную функцию: f(x) = sin(x^2 + 1)
# Найдите градиент df/dx
# Проверьте результат с помощью torch.autograd.grad

x = torch.tensor(2.0, requires_grad=True)
f = torch.sin(x ** 2 + 1)
# df/dx = 2 * x * cos(x^2 + 1)
print(2 * x * torch.cos(x ** 2 + 1))
grad = torch.autograd.grad(f, x)
grad

tensor(1.1346, grad_fn=<MulBackward0>)


(tensor(1.1346),)

# Задание 3: Сравнение производительности CPU vs CUDA

3.1 Подготовка данных

In [23]:
# Создайте большие матрицы размеров:
# - 64 x 1024 x 1024
# - 128 x 512 x 512
# - 256 x 256 x 256
# Заполните их случайными числами
A = torch.randn((64, 1024, 1024))
B = torch.randn((128, 512, 512))
C = torch.randn((256, 256, 256))
D = torch.randn((1024, 1024, 1024))
E = torch.randn((64, 64, 64))

if torch.cuda.is_available():
    A_cuda = A.to('cuda')
    B_cuda = B.to('cuda')
    C_cuda = C.to('cuda')
    D_cuda = D.to('cuda')
    E_cuda = E.to('cuda')

3.2 Функция измерения времени

In [18]:
# Создайте функцию для измерения времени выполнения операций
def cuda_measurement(func, *args, **kwargs):
  torch.cuda.synchronize()
  start_event = torch.cuda.Event(enable_timing=True)
  end_event = torch.cuda.Event(enable_timing=True)

  start_event.record()
  result = func(*args, **kwargs)
  end_event.record()
  torch.cuda.synchronize()

  elapsed_time_ms = start_event.elapsed_time(end_event)
  return elapsed_time_ms

def cpu_measurement(func, *args, **kwargs):
  start = time.perf_counter()
  result = func(*args, **kwargs)
  end = time.perf_counter()
  elapsed_time_ms = (end - start) * 1000
  return elapsed_time_ms


3.3 Сравнение операций

In [19]:
# Сравните время выполнения следующих операций на CPU и CUDA:
# - Матричное умножение (torch.matmul)
# - Поэлементное сложение
# - Поэлементное умножение
# - Транспонирование
# - Вычисление суммы всех элементов

# Для каждой операции:
# 1. Измерьте время на CPU
# 2. Измерьте время на GPU (если доступен)
# 3. Вычислите ускорение (speedup)
# 4. Выведите результаты в табличном виде

def matmultiply(x, y):
  return torch.matmul(x, y)

def multiply(x, y):
  return torch.mul(x, y)

def transpose(x):
  return x.T

def sum_(x):
  return x.sum()

In [13]:
cuda_time = cuda_measurement(matmultiply, D_cuda, D_cuda)
cpu_time = cpu_measurement(matmultiply, D, D)
print(f'CUDA execution time of matmul: {cuda_time} milliseconds')
print(f'CPU execution time of matmul: {cpu_time} milliseconds')
print(f'Speedup is {cpu_time / cuda_time} times')

cpu
cuda:0
CUDA execution time of matmul: 637.564453125 milliseconds
CPU execution time of matmul: 20001.216255000003 milliseconds
Speedup is 31.371285141391958 times


In [24]:
cuda_time = cuda_measurement(matmultiply, E_cuda, E_cuda)
cpu_time = cpu_measurement(matmultiply, E, E)
print(f'CUDA execution time of matmul: {cuda_time} milliseconds')
print(f'CPU execution time of matmul: {cpu_time} milliseconds')
print(f'Speedup is {cpu_time / cuda_time} times')

CUDA execution time of matmul: 0.6371840238571167 milliseconds
CPU execution time of matmul: 0.8883379999815588 milliseconds
Speedup is 1.3941623875063782 times


In [21]:
cuda_time = cuda_measurement(multiply, D_cuda, D_cuda)
cpu_time = cpu_measurement(multiply, D, D)
print(f'CUDA execution time of mul: {cuda_time} milliseconds')
print(f'CPU execution time of mul: {cpu_time} milliseconds')
print(f'Speedup is {cpu_time / cuda_time} times')

CUDA execution time of mul: 35.255550384521484 milliseconds
CPU execution time of mul: 2123.772988999974 milliseconds
Speedup is 60.23939396312447 times


In [15]:
cuda_time = cuda_measurement(transpose, B_cuda)
cpu_time = cpu_measurement(transpose, B)
print(f'CUDA execution time of transpose: {cuda_time} milliseconds')
print(f'CPU execution time of transpose: {cpu_time} milliseconds')
print(f'Speedup is {cpu_time / cuda_time} times')

CUDA execution time of transpose: 0.3691520094871521 milliseconds
CPU execution time of transpose: 0.02475099999799113 milliseconds
Speedup is 0.06704826023397974 times


/tmp/ipython-input-12-656219395.py:21: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:3725.)
  return x.T


In [16]:
cuda_time = cuda_measurement(sum_, A_cuda)
cpu_time = cpu_measurement(sum_, A)
print(f'CUDA execution time of sum(): {cuda_time} milliseconds')
print(f'CPU execution time of sum(): {cpu_time} milliseconds')
print(f'Speedup is {cpu_time / cuda_time} times')

CUDA execution time of sum(): 37.85222244262695 milliseconds
CPU execution time of sum(): 22.383511999990446 milliseconds
Speedup is 0.5913394394191092 times


3.4 Анализ результатов

GPU дает прибавку к скорости умножение матриц, за счет параллельных вычислений

- Почему некоторые операции могут быть медленнее на GPU?
Не для всех операций параллельные вычисления могут быть эффективны
- Как размер матриц влияет на ускорение? На маленьких тензорах CPU быстрее
- Что происходит при передаче данных между CPU и GPU? PyTorch копирует данные в VRAM\RAM